on: [push]
name: tests
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Clone and checkout branch
              uses: actions/checkout@v1
            - name: Install dependencies
              run: make deps
            - name: Run tests
              run: make test
            - name: Build project
              run: make
